1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code, functions, and modules that helps you perform common tasks or solve specific problems without having to write the code from scratch. Think of it as a toolbox with tools ready for use.

1. **Efficiency**: Libraries save time by providing reusable code for common tasks. Instead of reinventing the wheel, you can use existing solutions that have been tested and optimized.

2. **Productivity**: Libraries often come with extensive documentation and examples, which can help you get things done faster and learn new techniques.

3. **Community Support**: Popular libraries are often supported by a large community of developers who contribute to the library, fix bugs, and provide updates. This can be very helpful for troubleshooting and improving your code.

4. **Specialization**: Some libraries are designed for specific tasks or fields, such as data analysis (e.g., Pandas), machine learning (e.g., TensorFlow, scikit-learn), web development (e.g., Django, Flask), and more. This specialization means you can leverage sophisticated functionality tailored to particular needs.

5. **Consistency**: Using libraries that are well-tested and widely used helps ensure that your code adheres to best practices and standards, which can improve its reliability and maintainability.

In summary, Python libraries are essential tools that enhance productivity, ensure code quality, and provide specialized functionality, allowing you to focus more on solving problems rather than writing boilerplate code.

2. What is the difference between Numpy array and List?

Numpy arrays and Python lists are both used to store collections of items, but they have different characteristics and are suited for different tasks.

### 1. **Performance:**

- **Numpy Array**: Numpy arrays are implemented in C and are highly optimized for performance. They support vectorized operations, meaning operations are performed on entire arrays at once without the need for explicit loops in Python. This results in faster computations, especially with large datasets.

- **Python List**: Python lists are more general-purpose and are not optimized for performance with numerical computations. Operations on lists are typically slower, especially for large-scale mathematical operations, as they involve explicit loops in Python.

### 2. **Data Types:**

- **Numpy Array**: Numpy arrays are homogeneous, meaning all elements must be of the same data type. This uniformity allows Numpy to perform operations more efficiently and is particularly useful for numerical and scientific computations.

- **Python List**: Python lists are heterogeneous, meaning they can contain elements of different types (e.g., integers, strings, objects). This flexibility can be useful but comes with performance trade-offs for numerical operations.

### 3. **Memory Usage:**

- **Numpy Array**: Numpy arrays are more memory-efficient than Python lists. They use less memory because they store data in a contiguous block of memory and are optimized for space.

- **Python List**: Python lists have higher memory overhead because they store additional information for each element (e.g., type information and references), which can lead to higher memory usage.

### 4. **Functionality:**

- **Numpy Array**: Numpy provides a wide range of functions and operations specifically for numerical computations, such as element-wise operations, matrix manipulations, statistical functions, and linear algebra operations. It also supports multidimensional arrays (i.e., arrays with more than one dimension).

- **Python List**: Python lists offer basic operations such as appending, inserting, and removing elements. They do not natively support advanced numerical operations, so you would need to use additional libraries or write custom code for these tasks.

### 5. **Indexing and Slicing:**

- **Numpy Array**: Numpy arrays support advanced indexing and slicing techniques, including boolean indexing and fancy indexing. They also support slicing in multiple dimensions.

- **Python List**: Python lists support basic indexing and slicing, but they do not offer the advanced slicing and indexing capabilities that Numpy arrays do.

### 6. **Size and Shape:**

- **Numpy Array**: Numpy arrays can be multi-dimensional and have a defined shape. Operations can be performed across different dimensions, which is useful for tasks such as image processing and scientific computations.

- **Python List**: Python lists are one-dimensional by default, though you can create nested lists to simulate multi-dimensional structures. Operations across nested lists can be cumbersome compared to Numpy arrays.


3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

Answer

- **Shape**: (3, 4)
- **Size**: 12
- **Dimension**: 2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [1]:
import numpy as np
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

first_row = array[0]

print("First row:", first_row)


First row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access the element at the third row and fourth column
element = array[2, 3]

print("Element at third row and fourth column:", element)

Element at third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
import numpy as np
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

odd_indexed_elements = array[1:, 1:]

print("Odd-indexed elements:\n", odd_indexed_elements)


Odd-indexed elements:
 [[ 6  7  8]
 [10 11 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [4]:
import numpy as np

matrix = np.random.rand(3, 3)

print("Random 3x3 matrix with values between 0 and 1:\n", matrix)


Random 3x3 matrix with values between 0 and 1:
 [[0.62797385 0.23828016 0.92869106]
 [0.97067381 0.59286279 0.66604988]
 [0.6742408  0.20074735 0.8069367 ]]


8. Describe the difference between np.random.rand and np.random.randn?


- **Distribution**:
  - `np.random.rand`: Uniform distribution over \([0, 1)\).
  - `np.random.randn`: Standard normal distribution (Gaussian) with mean \(0\) and standard deviation \(1\).

- **Range of Values**:
  - `np.random.rand`: Values are always between \(0\) and \(1\).
  - `np.random.randn`: Values can be any real number, following a bell curve centered around \(0\).

- **Use Cases**:
  - `np.random.rand`: Use when you need values in a specific range (e.g., for simulations or when normalizing data).
  - `np.random.randn`: Use when you need values with a normal distribution, such as for statistical modeling or simulations that assume normality.

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:

expanded_dims_array = np.expand_dims(array, axis=2)

print("Array with expanded dimensions:\n", expanded_dims_array)
print("New shape:", expanded_dims_array.shape)


Array with expanded dimensions:
 [[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
New shape: (3, 4, 1)


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
import numpy as np

array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

transposed_array = np.transpose(array)

print("Transposed array using np.transpose:\n", transposed_array)


Transposed array using np.transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1

1. Index wiLe multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A


In [9]:
import numpy as np

# Define the matrices
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise Multiplication
elementwise_multiplication = A * B
print("Element-wise Multiplication:")
print(elementwise_multiplication)

# Matrix Multiplication
matrix_multiplication = A @ B.T  # B.T is the transpose of B
print("Matrix Multiplication:")
print(matrix_multiplication)

# Addition
addition = A + B
print("Addition:")
print(addition)

# Subtraction
subtraction = A - B
print("Subtraction:")
print(subtraction)

# Division
epsilon = 1e-10
division = np.divide(A, B + epsilon)  # Adding epsilon to avoid division by zero
print("Division:")
print(division)


Element-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12.  Which function in Numpy can be used to swap the byte order of an array?

Answer

numpy.ndarray.byteswap(inplace=False)


13.  What is the significance of the np.linalg.inv function?

Answer
13. Significance of the np.linalg.inv Function
The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.

Significance:

1. Matrix Inversion:

It provides the inverse of a matrix
𝐴
A, which is a matrix
𝐴
−
1
A
−1
  such that
𝐴
⋅
𝐴
−
1
=
𝐼
A⋅A
−1
 =I, where
𝐼
I is the identity matrix.

2. Solving Linear Systems: Inverse matrices are used to solve linear systems of equations. For example, if you have a system
𝐴
⋅
𝑥
=
𝑏
A⋅x=b, you can solve for
𝑥
x using
𝑥
=
𝐴
−
1
⋅
𝑏
x=A
−1
 ⋅b.
3. Matrix Analysis: The inverse is a key concept in various fields like linear algebra, control theory, and numerical analysis.



14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data.

Functionality:
Reshaping: It allows you to create a new view of the array with a different shape while keeping the same data.
Order: You can specify the order of elements with the order parameter (C-style row-major order, F-style column-major order).

15. What is broadcasting in Numpy?


Broadcasting enables NumPy to perform element-wise operations on arrays of different shapes by stretching the smaller array across the larger array.
It avoids the need for explicit loops and improves performance.


Rules:

1. If arrays have different dimensions, prepend the shape of the smaller array with ones until they have the same number of dimensions.
2. The dimensions of the two arrays are compared element-wise. Two dimensions are compatible when:
* They are equal, or
* One of them is 1